{
    "BaseFileName":"${BaseFileName?js_string}",
    "DisableCopy":${DisableCopy?c},
    "DisablePrint":${DisablePrint?c},
    "DisableExport":${DisableExport?c},
    "HideExportOption":${HideExportOption?c},
    "HideSaveOption":${HideSaveOption?c},
    "HidePrintOption":${HidePrintOption?c},
    "OwnerId":"${OwnerId?js_string}",
    "Size":${Size?c},
    "UserId":"${UserId?js_string}",
    "UserCanWrite":${UserCanWrite?c},
    "UserFriendlyName":"${UserFriendlyName?js_string}",
    "Version":"${Version?js_string}"
}